#!/usr/bin/python3
from sys import argv


def factorize():
    argc = len(argv)
    if argc != 2:
        print("Usage: ./factors <file>")
        exit(1)
    file = open(argv[1], "r")
    for line in file:
        number = int(line)
        for i in range(2, ((number // 2) + 1)):
            if number % i == 0:
                print("{}={}*{}".format(number, number // i, i))
                break
        else:
            print("{}={}*1".format(number, number))
    file.close()


if __name__ == "__main__":
    factorize()
